<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>YouGrab</AssemblyName>
    <RootNamespace>YoutubeDownloader</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- App Icon -->
    <ApplicationIcon>app.ico</ApplicationIcon>

    <!-- Unused Framework Feature Switches -->
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <EventSourceSupport>false</EventSourceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\analytics_py\yt_backend.py" Link="analytics_py\yt_backend.py">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\build\YoutubeCore.dll" Link="YoutubeCore.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="..\analytics_py\yt_backend.py" Link="Resources\yt_backend.py" />
    <EmbeddedResource Include="..\..\build\YoutubeCore.dll" Link="Resources\YoutubeCore.dll" />
    <Resource Include="app.ico"/>
    <Resource Include="Resources\kakao_qr.png"/>
  </ItemGroup>

</Project>
